### ISSUE TITLE
Mqttclient not connecting to broker

### ISSUE THREAD

**Issue by JelenaKovacc** [esar/contiki-mqtt#14]
Broker/Border router is working. I can ping it. I use tunslip6 and connection is established. But, my clients never connect to router. Any help?

**Comment by tonnenpinguin** [comment]
are you sure you set the correct ip address with the correct prefix on the device?
is the mqtt broker showing any messages? (duplicate connection attempt, etc.)

**Comment by Jekibeki17** [comment]
I corrected ip adress and it worked till i close my virtual box. Today i started the same process, but when i start tunneling to Mosquitto, tunslip6 didn't create interface tun0 (in ipconfig didn't exit) and i can't ping my border-router. Can you help me? 
I apologise for my english :)
